name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: go vet
        run: go vet ./...
      - uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args:  --timeout=5m
